kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  namespace: prometheus-node-exporter
spec:
  selector:
      app: node-exporter
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9000
    targetPort: 9000
  type: NodePort
